[package]
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "js_to_oxc"
repository.workspace = true
version = "0.0.1"

[dependencies]
oxc = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
